services:
  ecommerce-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: ecommerce-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - ecommerce-network
    volumes:
      - esdata:/usr/share/elasticsearch/data

  ecommerce-api:
    build:
      context: .
      dockerfile: src/Ecommerce.Api/Dockerfile
    expose:
      - 5000
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          cpus: "0.5"
          memory: 50M        
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ES_CONNECTION=http://ecommerce-elasticsearch:9200
      - REDIS_CONNECTION=ecommerce-redis:6379
    networks:
      - ecommerce-network
    depends_on:
      - ecommerce-elasticsearch

  ecommerce-nginx:
    image: nginx:1.29.1-alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3333:3333
    networks:
      - ecommerce-network
    depends_on:
      - ecommerce-api

  ecommerce-influxdb:
    image: influxdb:1.8
    networks:
      - ecommerce-network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    depends_on:
      - ecommerce-nginx

  ecommerce-grafana:
    image: grafana/grafana:8.5.21
    networks:
      - ecommerce-network
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - ecommerce-influxdb

  ecommerce-k6-load-test:
    image: grafana/k6:1.2.1
    networks:
      - ecommerce-network
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://ecommerce-influxdb:8086/k6
    volumes:
      - ./tests/Ecommerce.Api.LoadTests:/scripts
    depends_on:
      - ecommerce-grafana

  ecommerce-redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  esdata:
